name: vespag
channels:
  - conda-forge
  - bioconda
  - nvidia
  - pytorch
dependencies:
  - python=3.10
  - pip
  - pip:
      - dvc==3.17.0
      - jaxtyping
      - joblib-progress
      - rich
      - tqdm
      - transformers
      - typing_extensions
      - wandb
  - funcy=1.17
  - h5py
  - joblib
  - MKL=2024.0
  - numpy
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pandas
  - polars
  - typer
  - matplotlib
  - seaborn
  - biopython
  - torchmetrics