datasets:
  train:
    human:
      fasta: data/train/human/sequences.fasta
      embeddings:
        prott5: data/train/human/prott5_embeddings.h5
        esm2: data/train/human/esm2_embeddings.h5
      gemme_archive: data/train/zipped/human_fasta.tar.gz
      splits:
        train: data/train/human/splits/train_full.csv
        val: data/train/human/splits/val_full.csv
    droso:
      fasta: data/train/droso/sequences.fasta
      embeddings:
        prott5: data/train/droso/prott5_embeddings.h5
        esm2: data/train/droso/esm2_embeddings.h5
      gemme_archive: data/train/zipped/droso_fasta.tar.gz
      splits:
        train: data/train/droso/splits/train_full.csv
        val: data/train/droso/splits/val_full.csv
    ecoli:
      fasta: data/train/ecoli/sequences.fasta
      embeddings:
        prott5: data/train/ecoli/prott5_embeddings.h5
        esm2: data/train/ecoli/esm2_embeddings.h5
      gemme_archive: data/train/zipped/ecoli_fasta.tar.gz
      splits:
        train: data/train/ecoli/splits/train_full.csv
        val: data/train/ecoli/splits/val_full.csv
    virus:
      fasta: data/train/virus/sequences.fasta
      embeddings:
        prott5: data/train/virus/backup/prott5_embeddings.h5
        esm2: data/train/virus/backup/esm2_embeddings.h5
      gemme_archive: data/train/zipped/virus_fasta.tar.gz
      splits:
        train: data/train/virus/backup/splits/train_full.csv
        val: data/train/virus/backup/splits/val_full.csv
    all:
      fasta: data/train/all/sequences.fasta
      embeddings:
        prott5: data/train/all/prott5_embeddings.h5
        esm2: data/train/all/esm2_embeddings.h5
      gemme_archive: data/train/zipped/all_fasta.tar.gz
      splits:
        full: data/train/all/splits/full.csv
        train: data/train/all/splits/train_full.csv
        val: data/train/all/splits/val_full.csv
  test:
    mega_dataset:
      fasta: data/test/mega_dataset/dataset3_unique_sequences.fasta
    mega_dataset_v1_rasp:
      fasta: data/test/mega_dataset_v1_rasp/rasp_unique_sequences.fasta
    proteingym_substitutions:
      fasta: data/test/proteingym_substitutions/unique_proteins.fasta

gemme:
  alphabet: "ACDEFGHIKLMNPQRSTVWY"

random:
  seed: 42

preprocessing:
  na_threshold: .5

splits:
  validation_size: 0.2

training:
  single_taxon:
    sampling_strategy: basic
  all_taxa:
    sampling_strategy: basic

eval:
  batch_size: 8192
  proteingym:
    reference_files:
      per_dms: data/test/proteingym_substitutions/reference.csv
    dms_directory: data/test/proteingym_substitutions/DMS_scores

models:
  fnn:
    architecture: fnn
    model_parameters:
      hidden_dims: [256, 64]
      dropout_rate: 0.2
    training_parameters:
      learning_rate: 0.0001
      batch_size:
        training: 25000
        validation: 8192
      epochs: 200
      val_every_epoch: 1
      checkpoint_every_epoch: ~

  fnn_1_layer:
    architecture: fnn
    model_parameters:
      hidden_dims: [256]
      dropout_rate: 0.2
    training_parameters:
      learning_rate: 0.0001
      batch_size:
        training: 25000
        validation: 8192
      epochs: 200
      val_every_epoch: 1
      checkpoint_every_epoch: ~

  linreg:
    architecture: fnn
    model_parameters:
      hidden_dims: []
      dropout_rate: 0.2
    training_parameters:
      learning_rate: 0.0001
      batch_size:
        training: 25000
        validation: 8192
      epochs: 200
      val_every_epoch: 1
      checkpoint_every_epoch: ~

  cnn:
    architecture: cnn
    model_parameters:
      n_channels: 256
      kernel_size: 7
      padding: 3
      fully_connected_layers: [ 256, 64 ]
      dropout:
        fnn: 0.2
        cnn: 0.2
    training_parameters:
      learning_rate: 0.0001
      batch_size:
        training: 25000
        validation: 8192
      epochs: 200
      val_every_epoch: 1
      checkpoint_every_epoch: ~
